language: c
compiler:
  - gcc
  - clang
sudo: false

addons:
  apt:
    packages:
    - libnl-3-dev
    - libnl-genl-3-dev
    - libnl-route-3-dev
    - libnetfilter-conntrack-dev
    - libgeoip-dev
    - liburcu-dev
    - libpcap-dev
    - libnet1-dev
    - libcli-dev

script:
  - CC=$CC ./configure && make CC=$CC
  - CC=$CC DISABLE_GEOIP=1 ./configure && make clean && make CC=$CC
  - CC=$CC DISABLE_ZLIB=1 ./configure && make clean && make CC=$CC
  - CC=$CC DISABLE_GEOIP=1 DISABLE_ZLIB=1 ./configure && make clean && make CC=$CC
