language: c
compiler:
  - gcc
  - clang
sudo: false

env:
  global:
    - secure: "fTrjH4X1FJaCMAZXVW+sQBuKPr2C+w/pEkIl8FVQZvGxsgpw3OQR28stWnT7VhSuRExUqxEmKcIZgJmU9OAlF/K5ZQkNnUdyQgeiNdhPEMhTCQ3eZv8Ar60UVtmvuzWUN4BP1TUHoBCjq4Wxt1t4QN49P1T7RdjEawCfh+OFZ9s="

addons:
  apt:
    packages:
    - libnl-3-dev
    - libnl-genl-3-dev
    - libnl-route-3-dev
    - libnetfilter-conntrack-dev
    - libgeoip-dev
    - liburcu-dev
    - libpcap-dev
    - libnet1-dev
    - libcli-dev
  coverity_scan:
    project:
      name: "netsniff-ng/netsniff-ng"
      description: "Build submitted via Travis CI"
    notification_email: tklauser@distanz.ch
    build_command_prepend: "./configure && make clean"
    build_command: "make"
    branch_pattern: coverity_scan

script:
  - CC=$CC ./configure && make CC=$CC
  - CC=$CC ./configure --disable-geoip && make clean && make CC=$CC
  - CC=$CC ./configure --disable-zlib && make clean && make CC=$CC
  - CC=$CC ./configure --disable-geoip --disable-zlib && make clean && make CC=$CC
  - CC=$CC ./configure --disable-libnl && make clean && make CC=$CC
